# Generated by Django 4.0.6 on 2022-08-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagon_type', models.CharField(choices=[('PK', 'plasskart'), ('KP', 'puke'), ('LK', 'lyuks'), ('ST', 'seat'), ('CM', 'comfort'), ('BN', 'business')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_price', to='trains.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.city')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AF', 'Afrosiyob'), ('SH', 'Sharq'), ('PS', 'Oddiy')], max_length=2)),
                ('type', models.CharField(choices=[('CK', 'CK'), ('PASS', 'PASS'), ('CKPCT', 'CKPCT')], max_length=5)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.ManyToManyField(to='trains.stationprice')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trains.train')),
            ],
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PK', 'plasskart'), ('KP', 'puke'), ('LK', 'lyuks'), ('ST', 'seat'), ('CM', 'comfort'), ('BN', 'business')], max_length=5)),
                ('seat_count', models.IntegerField()),
                ('number', models.IntegerField()),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='trains.voyage')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_time', models.DateTimeField(null=True, verbose_name='kelish vaqti')),
                ('leave_time', models.DateTimeField(null=True, verbose_name='ketish vaqti')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.city')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='trains.voyage')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
