# Generated by Django 4.0.6 on 2022-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='arrive_time',
            field=models.DateTimeField(null=True, verbose_name='kelish vaqti'),
        ),
        migrations.AlterField(
            model_name='station',
            name='leave_time',
            field=models.DateTimeField(null=True, verbose_name='ketish vaqti'),
        ),
    ]
