# Generated by Django 4.0.6 on 2022-08-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('passport', models.CharField(max_length=20)),
                ('from_city', models.CharField(max_length=50)),
                ('to_city', models.CharField(max_length=50)),
                ('seat_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wagon_type', models.CharField(max_length=10)),
                ('arrive_time', models.DateTimeField(null=True, verbose_name='jonash vaqti')),
                ('leave_time', models.DateTimeField(null=True, verbose_name='borish vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to='trains.voyage')),
                ('wagon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='trains.wagon')),
            ],
        ),
    ]
